x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: payments_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-payments_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-payments_db}"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging: *default-logging

  temporal-postgres:
    image: postgres:15-alpine
    container_name: temporal_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "${TEMPORAL_POSTGRES_PORT:-5433}:5432"
    volumes:
      - temporal_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging: *default-logging

  temporal:
    image: temporalio/auto-setup:1.24.2
    container_name: temporal
    restart: unless-stopped
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: temporal-postgres
    ports:
      - "7233:7233"
    depends_on:
      temporal-postgres:
        condition: service_healthy
    logging: *default-logging

  temporal-ui:
    image: temporalio/ui:2.27.0
    container_name: temporal_ui
    restart: unless-stopped
    depends_on:
      temporal:
        condition: service_started
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:8080
    ports:
      - "8080:8080"
    logging: *default-logging

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@postgres:5432/${POSTGRES_DB:-payments_db}?schema=public

      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_TASK_QUEUE: ${TEMPORAL_TASK_QUEUE:-payments-queue}

      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:docker
    logging: *default-logging


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments_temporal_worker
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@postgres:5432/${POSTGRES_DB:-payments_db}?schema=public

      # Temporal
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_TASK_QUEUE: ${TEMPORAL_TASK_QUEUE:-payments-queue}

      # Mercado Pago
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_started
      app:
        condition: service_started
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run temporal:worker
    logging: *default-logging

volumes:
  postgres_data:
  temporal_pgdata:
